[WIP] User can change ui language
CraftAcademy/newsroom_client-april-2020 pull request #14
Opened 2020-06-01 06:17 UTC by PaulineBA

We are thinking of doing more feature tests but not sure what and how to test...

2020-06-01 06:46 UTC, kermit-klein approved these changes

2020-06-01 06:50 UTC, erikbjoern commented
You've got one commit that says 'adds autodetect language functionality', and I see that you use it in i18n. Does it work automatically? Is there any way to test it? Other than that I don't think we can test much more.

2020-06-01 13:32 UTC, erikbjoern approved these changes

2020-06-02 08:49 UTC, oliverochman requested changes
LGTM

2020-06-02 08:59 UTC, jysmys approved these changes

2020-06-02 10:11 UTC, merged