Add environment variables to front end
CraftAcademy/newsroom_client-april-2020 pull request #16
Opened 2020-06-01 19:10 UTC by kermit-klein

[PT LINK](https://www.pivotaltracker.com/story/show/173016810)

Add environment variables

2020-06-02 06:59 UTC, ViaMarcus approved these changes

2020-06-02 10:03 UTC, erikbjoern approved these changes
You could remove the .env file from here though.

2020-06-02 14:47 UTC, faraznaeem requested changes
env file still in version control
clear git cache and remove that file before pushing

2020-06-03 07:32 UTC, ViaMarcus approved these changes

2020-06-03 12:35 UTC, faraznaeem approved these changes

2020-06-03 12:35 UTC, merged