Visitor can view all listed articles
CraftAcademy/newsroom_client-april-2020 pull request #3
Opened 2020-05-21 15:14 UTC by PaulineBA

[PT LINK](https://www.pivotaltracker.com/story/show/172888047)

User Story

```
As a Visitor
In order to choose an article to read
I would like to be able to see the articles listed on a page
```

## Changes proposed in this pull request:
* We have used class component as we were unsure about how to use the functional component. Is it still ok to use class component at this stage? We haven't refactored it, let us know if this is a must ;-)

## What I have learned working on this feature:
* How to center placeholder in a column with semantic

## Packages/Gems added
- Semantic-ui-react-css

## Screenshots [(Client)](https://www.pivotaltracker.com/story/show/172888047/comments/214527842)

2020-05-21 15:19 UTC, erikbjoern commented on cypress/integration/visitorCanViewAllListedArticles.feature.js
> +    cy.get("#header");
Could contain .contains('Daily News Sense')

2020-05-21 15:20 UTC, kermit-klein approved these changes

2020-05-21 15:24 UTC, erikbjoern requested changes
I left a few comments. Also - are you importing the stylesheet anywhere? Couldn't see it.

2020-05-21 15:24 UTC, erikbjoern commented on cypress/integration/visitorCanViewAllListedArticles.feature.js
> +      url: "http://localhost:3000/api/v1/articles",
We don't have a v1 namespace actually!

2020-05-21 15:24 UTC, erikbjoern commented on package.json
> +    "semantic-ui-react": "^0.88.2",
cross-check this with what you wrote in PR overview (small thing...)

2020-05-21 17:33 UTC, oliverochman requested changes

2020-05-21 17:33 UTC, oliverochman commented on cypress/integration/visitorCanViewAllListedArticles.feature.js
> +      response: "fixture:articleList.json",
we use snake_case for json files

2020-05-21 17:33 UTC, oliverochman commented on cypress/integration/visitorCanViewAllListedArticles.feature.js
> +    cy.get("#header");
out of scope for this feature

2020-05-21 17:33 UTC, oliverochman commented on src/components/ArticleList.jsx
> +export default class ArticleList extends Component {
we can have a session turning this component into a functional component with react hooks tomorrow

2020-05-21 18:15 UTC, jysmys commented on cypress/integration/visitorCanViewAllListedArticles.feature.js
> +      url: "http://localhost:3000/api/v1/articles",
ok good to know, thanks!

2020-05-21 19:29 UTC, kermit-klein commented on cypress/integration/visitorCanViewAllListedArticles.feature.js
> +      response: "fixture:articleList.json",
this hasn't been solved yet

2020-05-21 19:30 UTC, kermit-klein commented on cypress/integration/visitorCanViewAllListedArticles.feature.js
> +      url: "http://localhost:3000/api/v1/articles",
you forgot to change URL in index.js

2020-05-21 19:34 UTC, kermit-klein commented on src/components/Header.jsx
> +import "../css/Header.css"
Are we going to have multiple css files ?
I think we shouldn't

2020-05-22 07:15 UTC, erikbjoern requested changes

2020-05-22 07:15 UTC, erikbjoern commented on src/index.js
> +axios.defaults.baseURL = "http://localhost:3000/api/v1";
This url shouldn't contain /v1 either

2020-05-22 08:46 UTC, merged